name: Labs Prototypes CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version: [19.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Clean Installing dependencies
        run: npm run ci

      - name: Generating the build
        run: npm run build

      - name: Checking the code quality
        run: npm run lint
        continue-on-error: true

      - name: Checking the code formatting
        run: npm run check:format
        continue-on-error: true

      - name: Running tests
        run: npm run test
